[package]
name = "dockworker"
version = "0.1.0"
edition = "2024"

[features]
default = ["parser"]
deploy = [
    "bollard",
    "futures-util",
    "ipnet",
    "tempfile",
    "tar",
    "tokio",
    "uuid",
]
parser = []  # Base feature for just parsing

[dependencies]
# Core dependencies (always included)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
shell-words = "1.1"
thiserror = "1.0"

# Optional dependencies (only with deploy feature)
bollard = { version = "0.14", optional = true }
futures-util = { version = "0.3", optional = true }
ipnet = { version = "2.10.1", optional = true }
tar = { version = "0.4.43", optional = true }
tempfile = { version = "3.14.0", optional = true }
tokio = { version = "1.0", features = ["full"], optional = true }
uuid = { version = "1.0", optional = true, features = ["v4"] }

[dev-dependencies]
dockworker = { path = ".", features = ["parser", "deploy"] }
tokio = { version = "1.0", features = ["full"] }
pretty_assertions = "1.4.1"